Fix notification
Still very occasionally observing:

java.lang.RuntimeException: Performing stop of activity that is not resumed: {siyugu.homework/siyugu.homework.activity.HomeScreen}

Not sure what needs to be done to fix this.